In [1]:
import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize,sent_tokenize
import numpy as np
import matplotlib.pyplot as plt
from skimage.io import imread, imshow
from PIL import Image
from PIL import ImageFile
import os
from os import listdir
import glob
from sklearn.model_selection import train_test_split
import string
from nltk.stem import WordNetLemmatizer
from cleantext import clean
import warnings
import pickle
import skimage
from skimage import filters
from skimage import feature
from skimage.io import imread, imshow
from skimage.feature import hog
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
from sklearn import metrics
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from skimage.transform import resize
import contractions
warnings.filterwarnings('ignore')

In [284]:
#text=clean(text,fix_unicode=True,to_ascii=True,lower=True,no_urls=True,no_numbers=True, no_digits=True,
 #         no_currency_symbols=True,no_punct=True,replace_with_punct="",replace_with_url=" ",
  #        replace_with_number=" ", replace_with_digit=" ",replace_with_currency_symbol=" ")
    
   # text=re.sub(r'[^\w\s]','',text)
!pip install contractions

In [8]:
df=pd.read_csv(r"E:\final project\labels.csv")

In [9]:
df22=pd.read_csv(r"E:\final project\labels.csv")
save=[]
for i in df22['image_name']:
    save.append(i)

In [10]:
n=6991
for i in range(0,270):
    save.append("image_"+str(n)+".jpg")
    n+=1

In [11]:
df

Unnamed: 0      image_name  \
0              0     image_1.jpg   
1              1    image_2.jpeg   
2              2     image_3.JPG   
3              3     image_4.png   
4              4     image_5.png   
...          ...             ...   
6987        6987  image_6988.jpg   
6988        6988  image_6989.jpg   
6989        6989  image_6990.png   
6990        6990  image_6991.jpg   
6991        6991  image_6992.jpg   

                                               text_ocr  \
0     LOOK THERE MY FRIEND LIGHTYEAR NOW ALL SOHALIK...   
1     The best of #10 YearChallenge! Completed in le...   
2     Sam Thorne @Strippin ( Follow Follow Saw every...   
3                 10 Year Challenge - Sweet Dee Edition   
4     10 YEAR CHALLENGE WITH NO FILTER 47 Hilarious ...   
...                                                 ...   
6987  Tuesday is Mardi Gras Wednesday is Valentine's...   
6988  MUST WATCH MOVIES OF 2017 ITI Chennai memes MA...   
6989  LESS MORE TALKING PLANNING SODA JUNK FOOD COMP...   
6990  When I VERY have time is a fantasy No one has ...   
6991  The starting point for every good idea is "Wha...   

                                         text_corrected overall_sentiment  
0     LOOK THERE MY FRIEND LIGHTYEAR NOW ALL SOHALIK...     very_positive  
1     The best of #10 YearChallenge! Completed in le...     very_positive  
2     Sam Thorne @Strippin ( Follow Follow Saw every...          positive  
3                 10 Year Challenge - Sweet Dee Edition          positive  
4     10 YEAR CHALLENGE WITH NO FILTER 47 Hilarious ...           neutral  
...                                                 ...               ...  
6987  Tuesday is Mardi Gras Wednesday is Valentine's...           neutral  
6988  MUST WATCH MOVIES OF 2017 ITI Chennai memes MA...           neutral  
6989  LESS MORE TALKING PLANNING SODA JUNK FOOD COMP...          positive  
6990  When I have time is a fantasy. no one has time...     very_positive  
6991  The starting point for every good idea is "Wha...          positive  

[6992 rows x 5 columns]

In [1204]:
OpFile=open(r"E:\Downloads\add (1).pkl", 'rb')
data=pickle.load(OpFile)
OpFile.close()

In [1205]:
More=[]

for i in range(0,len(data)):
    s=str(data[i])
    if s[-3]!='0':
        More.append(str(data[i]))

In [1206]:
txtcor=df['text_corrected'].astype(str)


In [1207]:
img=df['image_name'].astype(str)

In [1208]:
del df['image_name']; del df['Unnamed: 0']; del df['text_ocr']

In [1210]:
for i in range(0,len(More)):
    More[i]=cleaning(More[i])
    More[i] =re.sub(r'[^\w\s]','',More[i])
    More[i]=re.sub('\s+',' ',More[i])

In [1209]:
def cleaning(text):
    text=clean(text,no_urls=True,replace_with_url="")
    words = word_tokenize(text)
    alphaOnly = [word for word in words if word.isalpha()]
    Low = [word.lower() for word in alphaOnly]
    stWords = set(stopwords.words('english'))
    cleanText = [word for word in Low if word not in stWords]
    cleanText=" ".join(cleanText)
    
    return cleanText

In [1211]:
for i in range(0, len(txtcor)):
    txtcor[i]=cleaning(txtcor[i])
    txtcor[i] =re.sub(r'[^\w\s]','',txtcor[i])
    txtcor[i]=re.sub('\s+',' ',txtcor[i])

In [1213]:
moreLbl=[]
for i in range(0,len(More)):
    moreLbl.append('negative')

In [1214]:
df['text_corrected']=txtcor

In [1215]:
df=df.append(pd.DataFrame({'text_corrected': More, 'overall_sentiment' : moreLbl}),sort=False, ignore_index=True)


In [1151]:
df.to_csv("CleanedData.csv")

In [1216]:
data=df['text_corrected'].astype(str)

In [1218]:
CleanFile=open(r"C:\Users\hp\Desktop\CleanText.pkl", 'wb')
pickle.dump(data,CleanFile)
CleanFile.close()    

In [12]:
OpFile=open(r"C:\Users\hp\Desktop\CleanText.pkl", 'rb')
Corr=pickle.load(OpFile)
OpFile.close()

6992

In [1342]:
imLbl=[]

In [3]:
df3=pd.read_csv(r"E:\Downloads\CleanedNewData.csv")

In [4]:
df3

Unnamed: 0                                     text_corrected  \
0              0  look friend lightyear sohalikut trend play yea...   
1              1  best yearchallenge completed less years kudus ...   
2              2  sam thorne strippin follow follow saw everyone...   
3              3                   year challenge sweet dee edition   
4              4  year challenge filter hilarious year challenge...   
...          ...                                                ...   
7257        7257              dropping acid salvador dali last time   
7258        7258          dad spiderman memes funny spiderman memes   
7259        7259                                               none   
7260        7260                                  crush enters room   
7261        7261                                          know know   

     overall_sentiment       ImageName  
0        very_positive     image_1.jpg  
1        very_positive    image_2.jpeg  
2             positive     image_3.JPG  
3             positive     image_4.png  
4              neutral     image_5.png  
...                ...             ...  
7257          negative  image_7256.jpg  
7258          negative  image_7257.jpg  
7259          negative  image_7258.jpg  
7260          negative  image_7259.jpg  
7261          negative  image_7260.jpg  

[7262 rows x 4 columns]

In [5]:
lbl=df3['overall_sentiment'].astype(str)
l={'very_positive':1,'positive':1,'very_negative':-1,'negative':-1, 'neutral':0}
y=lbl.map(l)
len(y)

7262

In [6]:
Saaf=df3['text_corrected'].astype(str)

In [7]:
vect=TfidfVectorizer()
X=vect.fit_transform(Saaf)

In [8]:
X_train, X_test, y_train, y_test =train_test_split(X, y, test_size=0.2, random_state=30,shuffle=True)
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5809, 11501)
Shape of y_train =  (5809,)
Shape of X_test =  (1453, 11501)
Shape of y_test =  (1453,)


In [9]:
from sklearn import tree
clf = tree.DecisionTreeClassifier(criterion='gini')
clf = clf.fit(X_train, y_train)

In [10]:
pred=clf.predict(X_test)
#print (pred)
clf.score(X_test,y_test)

0.503785271851342

In [12]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report 
print(confusion_matrix(y_test,pred))
print ("Accuracy : " , accuracy_score(y_test,pred)*100)  
print("Report : \n", classification_report(y_test, pred))
print("F1 Score : ",f1_score(y_test, pred, average='macro')*100)
#print (pred)
clf.score(X_test,y_test)

[[ 59  38  76]
 [ 25 140 262]
 [ 65 255 533]]
Accuracy :  50.3785271851342
Report : 
               precision    recall  f1-score   support

          -1       0.40      0.34      0.37       173
           0       0.32      0.33      0.33       427
           1       0.61      0.62      0.62       853

    accuracy                           0.50      1453
   macro avg       0.44      0.43      0.44      1453
weighted avg       0.50      0.50      0.50      1453

F1 Score :  43.67901630117794


0.503785271851342

In [13]:
from sklearn.neighbors import KNeighborsClassifier
clf1=KNeighborsClassifier(n_neighbors=5,weights='distance',algorithm='brute')
bal=['ball_tree', 'kd_tree', 'brute']
clf1.fit(X_train, y_train)
pred=clf1.predict(X_test)
clf1.score(X_test,y_test)

0.5320027529249828

In [14]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report 
print ("Accuracy : " , accuracy_score(y_test,pred)*100)  
print("Report : \n", classification_report(y_test, pred))
print("F1 Score : ",f1_score(y_test, pred, average='macro')*100)

Accuracy :  53.200275292498276
Report : 
               precision    recall  f1-score   support

          -1       0.41      0.32      0.36       173
           0       0.33      0.27      0.30       427
           1       0.62      0.71      0.66       853

    accuracy                           0.53      1453
   macro avg       0.45      0.43      0.44      1453
weighted avg       0.51      0.53      0.52      1453

F1 Score :  43.94804241500643


In [15]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(solver='newton-cg', class_weight='balanced').fit(X_train, y_train)
pred2=clf.predict(X_test)

In [16]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report 
print ("Accuracy : " , accuracy_score(y_test,pred2)*100)  
print("Report : \n", classification_report(y_test, pred2))
print("F1 Score : ",f1_score(y_test, pred2, average='macro')*100)

Accuracy :  48.03854094975912
Report : 
               precision    recall  f1-score   support

          -1       0.34      0.41      0.37       173
           0       0.32      0.35      0.34       427
           1       0.61      0.56      0.58       853

    accuracy                           0.48      1453
   macro avg       0.43      0.44      0.43      1453
weighted avg       0.50      0.48      0.49      1453

F1 Score :  43.158987916564065


In [83]:
from sklearn.ensemble import VotingClassifier
Pkl_Filename=r"C:\Users\hp\Desktop\Pickle_DT_Model.pkl"
with open(Pkl_Filename, 'rb') as file:  
    DecT = pickle.load(file)
    
Pkl_Filename=r"C:\Users\hp\Desktop\Pickle_KNN_Model.pkl"
with open(Pkl_Filename, 'rb') as file:  
    knn = pickle.load(file)
    
Pkl_Filename=r"C:\Users\hp\Desktop\Pickle_LR_Model.pkl"
with open(Pkl_Filename, 'rb') as file:  
    lr = pickle.load(file)    

In [84]:
total= VotingClassifier(estimators=[('d',DecT), ('k',knn), ('l',lr)])

In [85]:
total.fit(X_train, y_train)
pred = total.predict(X_test)

In [86]:
print ("Accuracy : " , accuracy_score(y_test,pred)*100)  
print("Report : \n", classification_report(y_test, pred))
print("F1 Score : ",f1_score(y_test, pred, average='macro')*100)

Accuracy :  53.200275292498276
Report : 
               precision    recall  f1-score   support

          -1       0.41      0.32      0.36       173
           0       0.33      0.27      0.30       427
           1       0.62      0.71      0.66       853

    accuracy                           0.53      1453
   macro avg       0.45      0.43      0.44      1453
weighted avg       0.51      0.53      0.52      1453

F1 Score :  43.94804241500643


In [2]:
ImageFile.LOAD_TRUNCATED_IMAGES=True

In [3]:
newDF=pd.read_csv(r"E:\Downloads\CleanedNewData.csv")

In [4]:
newDF

Unnamed: 0                                     text_corrected  \
0              0  look friend lightyear sohalikut trend play yea...   
1              1  best yearchallenge completed less years kudus ...   
2              2  sam thorne strippin follow follow saw everyone...   
3              3                   year challenge sweet dee edition   
4              4  year challenge filter hilarious year challenge...   
...          ...                                                ...   
7257        7257              dropping acid salvador dali last time   
7258        7258          dad spiderman memes funny spiderman memes   
7259        7259                                               none   
7260        7260                                  crush enters room   
7261        7261                                          know know   

     overall_sentiment       ImageName  
0        very_positive     image_1.jpg  
1        very_positive    image_2.jpeg  
2             positive     image_3.JPG  
3             positive     image_4.png  
4              neutral     image_5.png  
...                ...             ...  
7257          negative  image_7256.jpg  
7258          negative  image_7257.jpg  
7259          negative  image_7258.jpg  
7260          negative  image_7259.jpg  
7261          negative  image_7260.jpg  

[7262 rows x 4 columns]

In [103]:
path=(r"E:\final project\images\\")
im=os.listdir(path)
pics=[]
count=0

for i in im:
     a=imread(path+i, as_gray=True)
     a=resize(a,(150,150))
     a=feature.canny(a)
     a=list(a.flatten())
     pics.append(a)

In [105]:
names=[]
for i in im:
    names.append(i)

In [106]:
names[3]

'image_1000.png'

In [136]:
Open=open(r"E:\GrayImages.pkl", 'wb')
pickle.dump(pics,Open)
Open.close()

In [137]:
Open=open(r"E:\GrayImages.pkl", 'rb')
images=pickle.load(Open)
Open.close()

In [138]:
dfImg=pd.DataFrame()
dfImg.insert(0,'Name',names)
dfImg.insert(1,'Arrays',images)
dfImg

Name                                             Arrays
0        image_1.jpg  [False, False, False, False, False, False, Fal...
1       image_10.png  [False, False, False, False, False, False, Fal...
2      image_100.jpg  [False, False, False, False, False, False, Fal...
3     image_1000.png  [False, False, False, False, False, False, Fal...
4     image_1001.png  [False, False, False, False, False, False, Fal...
...              ...                                                ...
6987  image_995.jpeg  [False, False, False, False, False, False, Fal...
6988   image_996.jpg  [False, False, False, False, False, False, Fal...
6989   image_997.jpg  [False, False, False, False, False, False, Fal...
6990   image_998.jpg  [False, False, False, False, False, False, Fal...
6991   image_999.png  [False, False, False, False, False, False, Fal...

[6992 rows x 2 columns]

In [139]:
dfImg['sort'] = dfImg['Name'].str.extract('(\d+)', expand=False).astype(int)
dfImg.sort_values('sort',inplace=True, ascending=True)
dfImg = dfImg.drop('sort', axis=1)
dfImg

Name                                             Arrays
0        image_1.jpg  [False, False, False, False, False, False, Fal...
1111    image_2.jpeg  [False, False, False, False, False, False, Fal...
2222     image_3.JPG  [False, False, False, False, False, False, Fal...
3333     image_4.png  [False, False, False, False, False, False, Fal...
4444     image_5.png  [False, False, False, False, False, False, Fal...
...              ...                                                ...
6653  image_6988.jpg  [False, False, False, False, False, False, Fal...
6654  image_6989.jpg  [False, False, False, False, False, False, Fal...
6656  image_6990.png  [False, False, False, False, False, False, Fal...
6657  image_6991.jpg  [False, False, False, False, False, False, Fal...
6658  image_6992.jpg  [False, False, False, False, False, False, Fal...

[6992 rows x 2 columns]

In [140]:
dfImg

Name                                             Arrays
0        image_1.jpg  [False, False, False, False, False, False, Fal...
1111    image_2.jpeg  [False, False, False, False, False, False, Fal...
2222     image_3.JPG  [False, False, False, False, False, False, Fal...
3333     image_4.png  [False, False, False, False, False, False, Fal...
4444     image_5.png  [False, False, False, False, False, False, Fal...
...              ...                                                ...
6653  image_6988.jpg  [False, False, False, False, False, False, Fal...
6654  image_6989.jpg  [False, False, False, False, False, False, Fal...
6656  image_6990.png  [False, False, False, False, False, False, Fal...
6657  image_6991.jpg  [False, False, False, False, False, False, Fal...
6658  image_6992.jpg  [False, False, False, False, False, False, Fal...

[6992 rows x 2 columns]

In [141]:
lb=newDF['overall_sentiment'].astype(str)
l={'very_positive':1,'positive':1,'very_negative':-1,'negative':-1, 'neutral':0}
y2=lb.map(l)
len(y2)

7262

In [142]:
newImg=[]
for i in dfImg.index:
    newImg.append(dfImg['Arrays'].loc[i])

In [143]:
change=[]
nn=newDF['ImageName'].astype(str)
ee=newDF['overall_sentiment'].astype(str)
for i in range (0,3049):
    if ee[i]=='negative' or ee[i]=='very_negative':
        change.append(nn[i])

In [144]:
path=(r"E:\final project\images\\")

In [145]:
for i in range(0,len(change)):
    a=imread(path+change[i], as_gray=True)
    a=np.flipud(a)
    a=resize(a,(150,150))
    a=feature.canny(a)
    a=list(a.flatten())
    newImg.append(a)
    

In [9]:
lb=newDF['overall_sentiment'].astype(str)
l={'very_positive':1,'positive':1,'very_negative':-1,'negative':-1, 'neutral':0}
y2=lb.map(l)
len(y2)

7262

In [6]:
newFile=open(r"E:\CannyImages2.pkl", 'rb')
dataImg2=pickle.load(newFile)
newFile.close()

In [7]:
newFile=open(r"E:\CannyImages.pkl", 'rb')
dataImg=pickle.load(newFile)
newFile.close()

In [10]:
X_train, X_test, y_train, y_test =train_test_split(dataImg2, y2, test_size=0.2, random_state=30,shuffle=True)

In [77]:
from sklearn.svm import SVC
clf=SVC(gamma='auto')
clf= clf.fit(X_train, y_train)

In [79]:
pred3=clf.predict(X_test)

In [80]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report 
print(confusion_matrix(y_test,pred3))
print ("Accuracy : " , accuracy_score(y_test,pred3)*100)  
print("Report : \n", classification_report(y_test, pred3))
print("F1 Score : ",f1_score(y_test, pred3, average='macro')*100)

[[ 50   0 123]
 [  0   0 427]
 [  0   0 853]]
Accuracy :  62.14728148657949
Report : 
               precision    recall  f1-score   support

          -1       1.00      0.29      0.45       173
           0       0.00      0.00      0.00       427
           1       0.61      1.00      0.76       853

    accuracy                           0.62      1453
   macro avg       0.54      0.43      0.40      1453
weighted avg       0.48      0.62      0.50      1453

F1 Score :  40.154538901080265


In [84]:
import pickle
Pkl_Filename = r"E:\Pickle_SVM_Model.pkl"  
with open(Pkl_Filename, 'rb') as file:  
    clf7= pickle.load(file)

In [88]:
import pickle
Pkl_Filename = r"E:\Pickle_SVM_Model_Pred.pkl"  

with open(Pkl_Filename, 'rb') as file:  
    pred5= pickle.load(file)

In [89]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report 
print ("Accuracy : " , accuracy_score(y_test,pred5)*100)  
print("Report : \n", classification_report(y_test, pred5))
print("F1 Score : ",f1_score(y_test, pred5, average='macro')*100)

Accuracy :  62.14728148657949
Report : 
               precision    recall  f1-score   support

          -1       1.00      0.29      0.45       173
           0       0.00      0.00      0.00       427
           1       0.61      1.00      0.76       853

    accuracy                           0.62      1453
   macro avg       0.54      0.43      0.40      1453
weighted avg       0.48      0.62      0.50      1453

F1 Score :  40.154538901080265


In [117]:
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier

In [118]:
clf6=RandomForestClassifier()
clf6= clf6.fit(X_train, y_train)

In [119]:
pred6=clf6.predict(X_test)

In [120]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report 
print ("Accuracy : " , accuracy_score(y_test,pred6)*100)  
print("Report : \n", classification_report(y_test, pred6))
print("F1 Score : ",f1_score(y_test, pred6, average='macro')*100)

Accuracy :  62.14728148657949
Report : 
               precision    recall  f1-score   support

          -1       1.00      0.29      0.45       173
           0       0.00      0.00      0.00       427
           1       0.61      1.00      0.76       853

    accuracy                           0.62      1453
   macro avg       0.54      0.43      0.40      1453
weighted avg       0.48      0.62      0.50      1453

F1 Score :  40.154538901080265


In [125]:
import pickle
Pkl_Filename = r"E:\Pickle_FTER_Model.pkl"  

with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(clf6,file)

In [126]:
import pickle
Pkl_Filename = r"E:\Pickle_FTER_Model_Pred.pkl"  

with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(pred6,file)

In [11]:
from sklearn.ensemble import AdaBoostClassifier

In [12]:
clf12=AdaBoostClassifier()


In [13]:
clf12.fit(X_train,y_train)

AdaBoostClassifier()

In [14]:
pred12=clf12.predict(X_test)

In [15]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report 
print ("Accuracy : " , accuracy_score(y_test,pred12)*100)  
print("Report : \n", classification_report(y_test, pred12))
print("F1 Score : ",f1_score(y_test, pred12, average='macro')*100)

Accuracy :  62.14728148657949
Report : 
               precision    recall  f1-score   support

          -1       1.00      0.29      0.45       173
           0       0.00      0.00      0.00       427
           1       0.61      1.00      0.76       853

    accuracy                           0.62      1453
   macro avg       0.54      0.43      0.40      1453
weighted avg       0.48      0.62      0.50      1453

F1 Score :  40.154538901080265


In [16]:
import pickle
Pkl_Filename = r"E:\Pickle_ADA_Model.pkl"  

with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(clf12,file)

In [17]:
from sklearn.ensemble import VotingClassifier
Pkl_Filename=r"C:\Users\hp\Desktop\Pickle_DT_Model.pkl"
with open(Pkl_Filename, 'rb') as file:  
    DecT = pickle.load(file)
    
Pkl_Filename=r"C:\Users\hp\Desktop\Pickle_KNN_Model.pkl"
with open(Pkl_Filename, 'rb') as file:  
    knn = pickle.load(file)
    
Pkl_Filename=r"C:\Users\hp\Desktop\Pickle_LR_Model.pkl"
with open(Pkl_Filename, 'rb') as file:  
    lr = pickle.load(file)    


Pkl_Filename = r"E:\Pickle_ADA_Model.pkl"  
with open(Pkl_Filename, 'rb') as file:  
    ada=pickle.load(file)
    

Pkl_Filename = r"E:\Pickle_FTER_Model.pkl"  
with open(Pkl_Filename, 'rb') as file:  
    ftr=pickle.load(file)

Pkl_Filename = r"E:\Pickle_SVM_Model.pkl"  
with open(Pkl_Filename, 'rb') as file:  
    SVM= pickle.load(file)

In [21]:
total= VotingClassifier(estimators=[('d',DecT), ('k',knn), ('l',lr),('a',ada),('f',ftr),('s',SVM)])

In [22]:
total.fit(X_train, y_train)
pred = total.predict(X_test)

In [24]:
print("F1 Score : ",f1_score(y_test, pred, average='macro')*100)

F1 Score :  40.154538901080265


In [25]:
Pkl_Filename = r"E:\Pickle_VC_Model.pkl"  
with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(total,file)

    
Pkl_Filename = r"E:\Pickle_VC_Model_Pred.pkl"  
with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(pred,file)

In [26]:
Pkl_Filename = r"E:\Pickle_VC_Model.pkl"  
with open(Pkl_Filename, 'rb') as file:  
    T= pickle.load(file)

    
Pkl_Filename = r"E:\Pickle_VC_Model_Pred.pkl"  
with open(Pkl_Filename, 'rb') as file:  
    o= pickle.load(file)

In [27]:
print("F1 Score : ",f1_score(y_test, o, average='macro')*100)

F1 Score :  40.154538901080265
